---
title: "NLP Sandbox Participation Dashboard"
author: "Andrew Lamb"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
params:
  source_table_synapse_id: ""
---

```{r setup, include=FALSE}
library(flexdashboard)
library(magrittr)
```

```{r, message=FALSE, include=FALSE}
synapser::synLogin()

submission_table <- 
  params$source_table_synapse_id %>% 
  stringr::str_c("select * from ", .) %>% 
  synapser::synTableQuery() %>% 
  purrr::pluck("filepath") %>% 
  readr::read_csv() %>% 
  dplyr::mutate(
    "datetime" = lubridate::as_datetime(
      .data$createdOn/1000, origin = "1970-01-01"
    ),
    "date" = lubridate::ymd(lubridate::floor_date(.data$datetime, "day")),
    "year" = forcats::as_factor(lubridate::year(.data$datetime)),
    "month" = lubridate::month(.data$datetime, label = TRUE, abbr = TRUE)
  ) 

current_year <- as.character(lubridate::year(lubridate::now()))
previous_year <- as.character(lubridate::year(lubridate::now() - lubridate::dyears(1)))

year_month_table <-
  submission_table %>% 
  dplyr::select("year", "month") %>% 
  dplyr::distinct() %>% 
  dplyr::mutate(
    "year" = forcats::fct_expand(.data$year, previous_year, current_year),
    "year" = forcats::fct_relevel(.data$year, previous_year, current_year)
  ) %>%
  tidyr::complete(.data$month, .data$year) %>%
  dplyr::mutate(
    "date" = lubridate::ymd(
      stringr::str_c(.data$year, .data$month, sep = " "),
      truncated = 1
    )
  ) %>% 
  dplyr::filter(
    .data$date > (lubridate::now() - lubridate::dyears(1)),
    .data$date <= (lubridate::now())
  ) %>% 
  dplyr::arrange(.data$year, .data$month) %>% 
  dplyr::mutate(
    "label" = forcats::as_factor(
      stringr::str_c(.data$month, .data$year, sep = " ")
    )
  ) %>% 
  dplyr::select("year", "month", "label")
```


Row {data-height=75}
-----------------------------------------------------------------------

### **Overview**

Submission data — from Synapse table `r params$source_table_id` — was downloaded using the `synapser` package for R on `r lubridate::now("UTC")` UTC. 



Row
-----------------------------------------------------------------------

### Number of Tasks Open

```{r}
n_unique_tasks     <- length(unique(submission_table$evaluationid))
flexdashboard::valueBox(n_unique_tasks , icon = "fa-cogs")
```

### Number of Submitters

```{r}
n_unique_submitters <- length(unique(submission_table$submitterid))
flexdashboard::valueBox(n_unique_submitters, icon = "fa-cogs")
```


Row
-----------------------------------------------------------------------
### Latest version of the NLP Sandbox schemas

```{r}
version <- gh::gh("GET /repos/nlpsandbox/nlpsandbox-schemas/releases")[[1]]$tag_name
flexdashboard::valueBox(version, icon = "fa-cogs")
```


### Number of Tools

```{r}
n_unique_tools      <- length(unique(submission_table$tool__name))
flexdashboard::valueBox(n_unique_tools, icon = "fa-cogs")
```



Row
-----------------------------------------------------------------------

### Number of Datasets

```{r}
n_unique_datasets   <- length(unique(submission_table$dataset_name))
flexdashboard::valueBox(n_unique_datasets, icon = "fa-cogs")
```

### Number of Data sites

```{r}
flexdashboard::valueBox(2, icon = "fa-cogs")
```

Row
-----------------------------------------------------------------------

### Number of Users

```{r}
n_users <- 3413388L %>% 
  synapser::synGetTeamMembers() %>% 
  synapser::as.list() %>% 
  length()
  
flexdashboard::valueBox(n_users, icon = "fa-cogs")
```

### Placeholder



Row 
-----------------------------------------------------------------------

### Number of submissions per month in the last year.

```{r}

n_submission_count_table <- submission_table %>% 
  dplyr::select("year", "month", "date") %>% 
  dplyr::filter(.data$date > (lubridate::now() - lubridate::dyears(1))) %>% 
  dplyr::group_by(.data$month, .data$year) %>% 
  dplyr::tally(name = "count") 


n_submission_table <- 
  dplyr::left_join(
    year_month_table, 
    n_submission_count_table,
    by = c("month", "year")
  ) %>% 
  dplyr::mutate(
    "count" = dplyr::if_else(
      is.na(.data$count),
      0L,
      .data$count
    )
  ) %>% 
  dplyr::select("count", "label")   
  


n_submission_plot <- plotly::plot_ly(
  n_submission_table,
  x = ~label,
  y = ~count,
  type = "bar"
) %>%
  plotly::layout(
    xaxis = list(title = "Month"),
    yaxis = list(title = "Submissions per month")
  )

n_submission_plot

```

### Number of unique submitters per month

```{r}

n_submitter_count_table <- submission_table %>% 
  dplyr::filter(.data$date > (lubridate::now() - lubridate::dyears(1))) %>% 
  dplyr::select("year", "month", "submitterid") %>% 
  dplyr::distinct() %>% 
  dplyr::group_by(.data$month, .data$year) %>% 
  dplyr::tally(name = "count") 

n_submitter_table <- 
  dplyr::left_join(
    year_month_table, 
    n_submitter_count_table,
    by = c("month", "year")
  ) %>% 
  dplyr::mutate(
    "count" = dplyr::if_else(
      is.na(.data$count),
      0L,
      .data$count
    )
  ) %>% 
  dplyr::select("count", "label")   
  


n_submitter_plot <- plotly::plot_ly(
  n_submitter_table,
  x = ~label,
  y = ~count,
  type = "bar"
) %>%
  plotly::layout(
    xaxis = list(title = "Month"),
    yaxis = list(title = "Unique submitters per month")
  )

n_submitter_plot
```

Row 
-----------------------------------------------------------------------

### Number of successful submissions in the last month.

```{r}
n_statuses <- submission_table %>%
  dplyr::filter(.data$datetime > (lubridate::now() - lubridate::dmonths(1))) %>% 
  dplyr::pull("status") 
  

flexdashboard::gauge(
  value = length(purrr::keep(n_statuses, ~.x == "ACCEPTED")),
  min = 0,
  max = length(n_statuses)
)

```

### Placeholder

